build:
	forge build
t:
	forge test
create:
	forge create CeramicAnchorServiceV2\
	 --contracts src/CeramicAnchorServiceV2.sol\
	 --private-key <private-key> --rpc-url https:/infura.io/<key>
testDeployment:
	cast call <address> "owner()" --rpc-url https://infura.io/<key>:
