version: '3.4'

services:
  cas_api:
    build: .
    environment:
      - NODE_ENV=dev
      - APP_MODE=server
      - APP_PORT=8081
      - USE_SMART_CONTRACT_ANCHORS=true

      - ANCHOR_CONTROLLER_ENABLED=false
      - ANCHOR_EXPIRATION_PERIOD=0
      - ANCHOR_SCHEDULE_EXPRESSION=0/1 * * * ? *

      - BLOCKCHAIN_CONNECTOR=ethereum
      - CERAMIC_API_URL=http://host.docker.internal:7007
      - ETH_GAS_LIMIT=4712388
      - ETH_GAS_PRICE=100000000000
      - ETH_NETWORK=goerli
      - ETH_OVERRIDE_GAS_CONFIG=false
      - ETH_WALLET_PK=0x16dd0990d19001c50eeea6d32e8fdeef40d3945962caf18c18c3930baa5a6ec9
      - ETH_CONTRACT_ADDRESS=0xD3f84Cf6Be3DD0EB16dC89c972f7a27B441A39f2

      - IPFS_API_URL=http://ipfs:5011
      - IPFS_API_TIMEOUT=10000

      - LOG_LEVEL=debug
      - LOG_TO_FILES=true
      - LOG_PATH=/usr/local/var/log
      - MERKLE_DEPTH_LIMIT=0

      - DB_NAME=anchor_db
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root

      - VALIDATE_RECORDS=false
    volumes:
      - '/usr/local/var/log:/usr/local/var/log'
    depends_on:
      - ipfs
      - database
    ports:
      - '8081:8081'
    networks:
      - internal

  cas_anchor:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - APP_MODE=anchor
      - APP_PORT=8081
      - USE_SMART_CONTRACT_ANCHORS=true

      - ANCHOR_CONTROLLER_ENABLED=false
      - ANCHOR_EXPIRATION_PERIOD=0
      - ANCHOR_SCHEDULE_EXPRESSION=0/1 * * * ? *

      - BLOCKCHAIN_CONNECTOR=ethereum
      - CERAMIC_API_URL=http://host.docker.internal:7007
      - ETH_GAS_LIMIT=4712388
      - ETH_GAS_PRICE=100000000000
      - ETH_NETWORK=goerli
      - ETH_OVERRIDE_GAS_CONFIG=false
      - ETH_WALLET_PK=0x16dd0990d19001c50eeea6d32e8fdeef40d3945962caf18c18c3930baa5a6ec9
      - ETH_CONTRACT_ADDRESS=0xD3f84Cf6Be3DD0EB16dC89c972f7a27B441A39f2

      - IPFS_API_URL=http://ipfs:5011
      - IPFS_API_TIMEOUT=10000

      - LOG_LEVEL=debug
      - LOG_TO_FILES=true
      - LOG_PATH=/usr/local/var/log
      - MERKLE_DEPTH_LIMIT=0

      - DB_NAME=anchor_db
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root

      - VALIDATE_RECORDS=false
    volumes:
      - '/usr/local/var/log:/usr/local/var/log'
    depends_on:
      - ipfs
      - database
      - cas_api
    networks:
      - internal

  ipfs:
    image: ceramicnetwork/ipfs-daemon
    volumes:
      - './export:/export'
      - './data/ipfs:/data/ipfs'
    ports:
      - '5011:5011'
      - '4001:4001'
      - '8080:8080'
    networks:
      - internal

  database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=anchor_db
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    networks:
      - internal

#  ganache:
#    image: trufflesuite/ganache-cli:latest
#    ports:
#      - "8545:8545"
#    volumes:
#      - ./data/ganache:/ganache_data
#    entrypoint:
#      - node
#      - /app/ganache-core.docker.cli.js
#      - --deterministic
#      - --db=/ganache_data
#      - --mnemonic
#      - 'move sense much taxi wave hurry recall stairs thank brother nut woman'
#      - --networkId
#      - '5777'
#      - --hostname
#      - '0.0.0.0'
#      - -l
#      - '80000000'
#      - --quiet
#    networks:
#      - internal

#  localstack:
#    image: localstack/localstack:latest
#    container_name: localstack_demo
#    ports:
#      - '4563-4584:4563-4584'
#      - '8055:8080'
#    environment:
#      - SERVICES=s3,rds
#      - DEBUG=1
#      - DATA_DIR=/tmp/localstack/data
#    volumes:
#      - './.localstack:/tmp/localstack'
#      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  internal:
    driver: bridge
