name: Publish release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of publish (one of: rc, full, both, hotfix)'
        required: true
        default: 'rc'

jobs:
  publish_full:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup environment
        id: set-vars
        run: |
          if [[ "${{ github.event.inputs.type }}" == "both" || "${{ github.event.inputs.type }}" == "full" ]]; then
            echo "::set-output name=full::true"
          elif [[ "${{ github.event.inputs.type }}" == "hotfix" ]]; then
            echo "::set-output name=full::true"
            echo "::set-output name=hotfix::true"
          fi
      -
        name: Setup Node
        if: ${{ steps.set-vars.outputs.full == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      -
        name: Checkout `main` branch
        if: ${{ steps.set-vars.outputs.full == 'true' }}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: main
      -
        name: Merge `release-candidate` -> `main`
        if: ${{ steps.set-vars.outputs.full == 'true' && steps.set-vars.outputs.hotfix != 'true' }}
        run: |
          git fetch origin release-candidate
          git merge origin/release-candidate
      -
        name: Initialize and build code
        if: ${{ steps.set-vars.outputs.full == 'true' }}
        run: |
          npm set unsafe-perm true
          npm ci && npm run build
      -
        name: Publish release
        if: ${{ steps.set-vars.outputs.full == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name ${{ github.actor }}
          npm run release -- --ci --github.release --no-npm
      -
        name: Update and push code to `release-candidate` and `develop`
        if: ${{ steps.set-vars.outputs.full == 'true' }}
        run: |
          git checkout -B release-candidate refs/remotes/origin/release-candidate
          git merge origin/main
          git push
          git checkout -B develop refs/remotes/origin/develop
          git merge origin/main
          git push
      -
        name: Send Discord notification
        if: ${{ steps.set-vars.outputs.full == 'true' }}
        run: |
          # Prepare notification body
          echo '{"embeds":[{"title":"**Release Published**","description":"```' > embed.json
          git log -2 --pretty=%B >> embed.json
          echo '```","color":3581519}]}' >> embed.json
          sed -i '2,5d' embed.json
          sed -i '2 s/\ -/-/' embed.json
          sed -i '3,$ s/\-/\\n-/' embed.json
          cat embed.json

          # Send notification
          res=$(curl -X POST ${{ secrets.DISCORD_RELEASE_WEBHOOK }} -H "Content-Type: application/json" -d @embed.json) || exit 1

  publish_rc:
    runs-on: ubuntu-latest
    needs: publish_full
    steps:
      -
        name: Setup environment
        id: set-vars
        run: |
          if [[ "${{ github.event.inputs.type }}" == "both" || "${{ github.event.inputs.type }}" == "rc" ]]; then
            echo "::set-output name=rc::true"
          fi
      -
        name: Setup Node
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      -
        name: Checkout `release-candidate` branch
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: release-candidate
      -
        name: Merge `develop` -> `release-candidate`
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        run: |
          git fetch origin develop
          git merge origin/develop
      -
        name: Initialize and build code
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        run: |
          npm set unsafe-perm true
          npm ci && npm run build
      -
        name: Publish pre-release
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name ${{ github.actor }}
          npm run release -- --ci --preRelease=rc --github.release --no-npm
      -
        name: Update and push code to `develop`
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        run: |
          git checkout -B develop refs/remotes/origin/develop
          git merge origin/release-candidate
          git push
      -
        name: Send Discord notification
        if: ${{ steps.set-vars.outputs.rc == 'true' }}
        run: |
          # Prepare notification body
          echo '{"embeds":[{"title":"**Release Candidate Published**","description":"```' > embed.json
          git log -1 --pretty=%B >> embed.json
          echo '```","color":3581519}]}' >> embed.json
          sed -i '2,3d' embed.json
          sed -i '2 s/\ -/-/' embed.json
          sed -i '3,$ s/\-/\\n-/' embed.json
          cat embed.json

          # Send notification
          res=$(curl -X POST ${{ secrets.DISCORD_RELEASE_WEBHOOK }} -H "Content-Type: application/json" -d @embed.json) || exit 1
